#!/usr/bin/env python3
import asyncio
from grader.tcp import Servidor, Conexao
from trata_dados import enviar_dados_tratados
from palavras_reservadas import retornar_mensagem_de_ping
import re

WORDS = {b'PING': retornar_mensagem_de_ping}
setattr(Conexao, 'residuos', b'') 
total = 1

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)

    enviar_dados_tratados(conexao, dados)

def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
